### ISSUE TITLE
[BUG] (bug summary)Error: Build environment 'mega2560' is incompatible with BOARD_BTT_SKR_MINI_E3_V3_0

### ISSUE THREAD

**Issue by DutchPixelDesign** [thisiskeithb/EnderAIO#5]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Normally I change the board name in platformio.ini. But now I only opened the Ender_AIO_Configuration.h. 
I have a Ender 3 Pro with SK3 Mini 3 V3 board. I'm still new with this and learning. So sorry if I did a noob thing.

It keeps saying at my autobuild that Architectures  are the Atmega 2560, 1280 and the Environments are the 2560 en 1280.

This is the code: from Ender_AIO_Configuration:
[platformio]
src_dir      = Marlin
boards_dir   = buildroot/share/PlatformIO/boards
default_envs = STM32G0B1RE_btt
include_dir  = Marlin

#
# Just print the dependency tree
#
[env:include_tree]
platform         = atmelavr
board            = megaatmega2560
build_flags      = -c -H -std=gnu++11 -Wall -Os -D__MARLIN_FIRMWARE__
build_src_filter = +<src/MarlinCore.cpp>

This is the error that I get:
platformio run --silent -e mega2560 ; echo "done" >|"/var/folders/2w/xbsfk62d38b74xnfcvv7v6t80000gn/T/ipc"
dutchpixel@iMac-van-Dutch EnderAIO-E3-AIO-bugfix-2.1.x % platformio run --silent -e mega2560 ; echo "done" >|"/var/folders/2w/xbsfk62d38b74xnfcvv7v6t80000gn/T/ipc"
Error: Build environment 'mega2560' is incompatible with BOARD_BTT_SKR_MINI_E3_V3_0. Use one of these environments: STM32G0B1RE_btt, STM32G0B1RE_btt_xfer
============================================================================================= [FAILED] Took 1.18 seconds =============================================================================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:01.177
======================================================================================= 1 failed, 0 succeeded in 00:00:01.177 =======================================================================================
dutchpixel@iMac-van-Dutch EnderAIO-E3-AIO-bugfix-2.1.x % 

### Bug Timeline

Bug

### Version of Marlin Firmware

Marlin Ender AIO 2.1.X

### Printer model

Creality Ender 3 Pro

### Electronics

SKR Mini E3.0 V3

### Other add-ons

Biqu Microprobe V2

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Because I have the Bique Microprobe V2 I edited these settings

`/**
 * Probe Enable / Disable
 * The probe only provides a triggered signal when enabled.
 */
#define PROBE_ENABLE_DISABLE
#if ENABLED(PROBE_ENABLE_DISABLE)
  #define PROBE_ENABLE_PIN SERVO0_PIN   // Override the default pin here
#endif

#define BIQU_MICROPROBE_V2  // Triggers LOW

#define Z_MIN_PROBE_PIN PC14`

Here are the configuration.h, configuration_adv.h and Ender_AIO_Configuration.h files. 

[Files.zip](https://github.com/thisiskeithb/EnderAIO/files/14024946/Files.zip)

**Comment by thisiskeithb** [comment]
You can't use the Auto Build Marlin plugin with this fork, so you will need to run the Build command manually using the check mark in the lower-left side of VSCode after setting the correct environment in `platformio.ini`:

<img width="255" alt="image" src="https://github.com/thisiskeithb/EnderAIO/assets/13375512/5f67ecb1-0707-45c2-bb03-77584b2f6b88">

---

The MicroProbe is not supported in this fork at this time: https://github.com/thisiskeithb/EnderAIO/discussions/4
